// approve request handler — pure, testable (no Deno globals, no third-party deps).
//
// Talks to PostgREST directly with the service-role key (same as the rest of the
// repo's Supabase access), so there is no third-party runtime dependency to audit.
//
// Security notes (audit 2026-09):
//   * Only GET/HEAD are accepted (the links live in an email).
//   * `id`, `day` and `token` are validated for shape before they reach a filter.
//   * Every write is checked: a failed UPDATE now redirects to the error page
//     instead of claiming success.
//   * Each decision is logged (id/day/action/outcome, never the token) so approvals
//     can be audited from the function log.

export const PAGE = "https://alon3153.github.io/upe-social-publisher/r.html";
const NET: Record<string, string> = { facebook: "Facebook", instagram: "Instagram", linkedin: "LinkedIn", tiktok: "TikTok" };

// Tokens are generated by the database and only ever compared, never used in a
// filter — so the shape check is deliberately loose: printable ASCII, no spaces.
const TOKEN_RE = /^[\x21-\x7e]{1,256}$/;
const ID_RE = /^[A-Za-z0-9_\-]{1,64}$/;
const DAY_RE = /^\d{1,9}$/;

export interface Env {
  sbUrl: string;
  sbKey: string;
  fetch: typeof fetch;
  now: () => number;
  log: (...args: unknown[]) => void;
}

interface Row {
  id: string | number;
  day: string | number;
  token: string;
  status: string;
  network: string;
}

export function redirect(s: string, net = "", day: string | number = ""): Response {
  const q = new URLSearchParams({ s, net, day: String(day) });
  return new Response(null, {
    status: 302,
    headers: { Location: `${PAGE}?${q}`, "cache-control": "no-store", "referrer-policy": "no-referrer" },
  });
}

function headers(env: Env, extra: Record<string, string> = {}): Record<string, string> {
  return { apikey: env.sbKey, Authorization: `Bearer ${env.sbKey}`, ...extra };
}

async function select(env: Env, params: Record<string, string>): Promise<Row[]> {
  const q = new URLSearchParams({ select: "id,day,token,status,network", ...params });
  const r = await env.fetch(`${env.sbUrl}/rest/v1/post_approvals?${q}`, { headers: headers(env) });
  if (!r.ok) throw new Error(`select ${r.status}`);
  return await r.json();
}

async function update(env: Env, filter: Record<string, string>, body: Record<string, unknown>): Promise<void> {
  const q = new URLSearchParams(filter);
  const r = await env.fetch(`${env.sbUrl}/rest/v1/post_approvals?${q}`, {
    method: "PATCH",
    headers: headers(env, { "Content-Type": "application/json", Prefer: "return=minimal" }),
    body: JSON.stringify(body),
  });
  if (!r.ok) throw new Error(`update ${r.status}`);
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

export async function handle(req: Request, env: Env): Promise<Response> {
  if (req.method !== "GET" && req.method !== "HEAD") {
    return new Response("method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
  }
  const url = new URL(req.url);
  const action = (url.searchParams.get("action") || "approve").toLowerCase();
  const token = url.searchParams.get("token") || "";
  if (!TOKEN_RE.test(token)) {
    env.log("approve: malformed or missing token", { action });
    return redirect("err");
  }
  if (!["approve", "reject", "approve_all"].includes(action)) {
    env.log("approve: unknown action", { action: action.slice(0, 40) });
    return redirect("err");
  }

  try {
    // ── Batch approve: approve every still-pending post for a given day ──
    if (action === "approve_all") {
      const day = url.searchParams.get("day") || "";
      if (!DAY_RE.test(day)) return redirect("err");
      const rows = await select(env, { day: `eq.${day}` });
      if (rows.length === 0) return redirect("err");
      // token must match one row from this day's batch (proves email receipt)
      if (!rows.some((r) => typeof r.token === "string" && timingSafeEqual(r.token, token))) {
        env.log("approve: approve_all token mismatch", { day });
        return redirect("err");
      }
      // Only pending rows. Excluding published/approved is not enough: it let
      // `rejected` through, so one "approve all" click revived posts Alon had
      // explicitly declined (seen 14.08.2026 on days 9101/9102/9103).
      const ids = rows.filter((r) => r.status === "pending").map((r) => String(r.id));
      if (ids.length > 0) {
        await update(env, { id: `in.(${ids.join(",")})` },
          { status: "approved", approved_at: new Date(env.now()).toISOString() });
      }
      env.log("approve: approve_all", { day, approved: ids.length });
      return redirect("all", "", day);
    }

    // ── Single post approve / reject ──
    const id = url.searchParams.get("id") || "";
    if (!ID_RE.test(id)) return redirect("err");
    const rows = await select(env, { id: `eq.${id}`, limit: "1" });
    const row = rows[0];
    if (!row || typeof row.token !== "string" || !timingSafeEqual(row.token, token)) {
      env.log("approve: token mismatch or unknown id", { id, action });
      return redirect("err");
    }
    const net = NET[row.network] || row.network;
    if (row.status === "published") return redirect("pub", net, row.day);
    if (row.status === "approved" && action === "approve") return redirect("dup", net, row.day);
    if (action === "reject") {
      await update(env, { id: `eq.${id}` }, { status: "rejected" });
      env.log("approve: rejected", { id, day: row.day, network: row.network });
      return redirect("rej", net, row.day);
    }
    await update(env, { id: `eq.${id}` },
      { status: "approved", approved_at: new Date(env.now()).toISOString() });
    env.log("approve: approved", { id, day: row.day, network: row.network });
    return redirect("ok", net, row.day);
  } catch (e) {
    env.log("approve: failure", String(e).slice(0, 300));
    return redirect("err");
  }
}
