"""Write generated pages into uproduction-astro and open an auto-merging PR."""
import subprocess
from pathlib import Path
import aeo_generate


def page_path(repo, page):
    return f"{repo}/src/content/{page['collection']}/{page['lang']}/{page['slug']}.md"


def write_pages(repo, pages):
    written = []
    for page in pages:
        path = Path(page_path(repo, page))
        path.parent.mkdir(parents=True, exist_ok=True)
        md = aeo_generate.to_markdown(page["frontmatter"], page["body"])
        path.write_text(md, encoding="utf-8")
        written.append(str(path.relative_to(repo)))
    return written


def publish(repo, pages, branch, date, runner=subprocess.run, dry_run=False):
    files = write_pages(repo, pages)
    if dry_run:
        return {"branch": branch, "files": files, "pr_url": None, "dry_run": True}

    def run(cmd, capture=False):
        return runner(cmd, cwd=repo, text=True,
                      stdout=(subprocess.PIPE if capture else None))

    run(["git", "checkout", "-B", branch])
    run(["git", "add", *files])
    run(["git", "commit", "-m", f"feat(aeo): GEO content {date} ({len(files)} pages)"])
    run(["git", "push", "-u", "origin", branch, "--force-with-lease"])
    title = f"AEO content {date}: {len(files)} pages"
    body = "Auto-generated by the weekly AEO/GEO loop. Closes measured visibility gaps."
    res = run(["gh", "pr", "create", "--title", title, "--body", body, "--head", branch], capture=True)
    pr_url = (res.stdout or "").strip().splitlines()[-1] if getattr(res, "stdout", "") else None
    return {"branch": branch, "files": files, "pr_url": pr_url, "dry_run": False}
